name: Desktop Build

on: [push]
jobs:
  package:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2-beta
      with:
        ref: ${GITHUB_REF##*/}
    # Authenticates packages to push to GPR
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.0.101' # SDK Version to use.
    - name: Build Project
      run: |
        cd src/Desktop/MaSchoeller.Extensions.Desktop/
        dotnet build

        