name: Tinkerforge Build

on: 
  push:
    paths:
      - 'src/Tinkerforge/**'
    # tags-ignore:
    #   - desktop/*
    #   - tinkerforge/*
    #   - universal/*
jobs:
  build:
    runs-on: windows-latest
    steps:

    - uses: actions/checkout@master
      with:
        ref: ${{ github.ref }}
    - uses: actions/setup-dotnet@v1.3.0
      with:
        dotnet-version: '3.1.100' # SDK Version to use.
    - name: Build Project
      run: |
        cd src/Tinkerforge/MaSchoeller.Extensions.Tinkerforge/
        dotnet build
