name: Tinkerforge Build

on: 
  push:
    paths:
      - 'src/Tinkerforge/**'
      - '.github/workflows/**'
    tags-ignore:
       - desktop/*
       - universal/*
jobs:
  build:
    runs-on: windows-latest
    steps:

    - uses: actions/checkout@master
      with:
        ref: ${{ github.ref }}
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.100' # SDK Version to use.
    - name: Build Project
      run: |
        cd src/Tinkerforge/MaSchoeller.Extensions.Tinkerforge/
        dotnet build
