name: Universal Deploy
on:
  push:
    tags:
    - universal/*

jobs:
  package:
    runs-on: windows-latest
    steps:
      - name: clone repo 
        uses: actions/checkout@master
        with:
            ref: ${{ github.ref }}
      - name: publish on version change
        uses: rohith/publish-nuget@v2
        with:
          PROJECT_FILE_PATH: src/Universal/MaSchoeller.Extensions.Universal/MaSchoeller.Extensions.Universal.csproj # Relative to repository root
          # VERSION_FILE_PATH: Directory.Build.props # Filepath with version info, relative to repository root. Defaults to project file
          # VERSION_REGEX: <Version>(.*)<\/Version> # Regex pattern to extract version info in a capturing group
          # TAG_COMMIT: true # Flag to enable / disalge git tagging
          # TAG_FORMAT: v* # Format of the git tag, [*] gets replaced with version
          NUGET_KEY: ${{secrets.nuget_key}} # nuget.org API key
        
