name: Universal Build

on: 
    push:
      tags-ignore:
        - desktop/*
        - tinkerforge/*
        - universal/*
      paths:
        - 'src/Universal/**'
jobs:
    build:
      runs-on: windows-latest
  
      steps:
      - name: clone repo 
        uses: actions/checkout@master
        with:
            ref: ${{ github.ref }}
      - name: Setup MSBuild.exe
        uses: warrenbuckley/Setup-MSBuild@v1
  
      - name: MSBuild
        working-directory: src/Universal
        run: msbuild /t:Restore /p:Configuration=Release MaSchoeller.Extensions.Universal.sln